name: "Build"

on:
  pull_request:
  push:

jobs:
  build:
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
    - uses: cachix/cachix-action@v14
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv
    - name: Run a multi-line command in the devenv shell
      shell: devenv shell bash -- -e {0}
      run: |
        hugo version
