name: "Build"

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: nixbuild/nix-quick-install-action@v29
    #- uses: cachix/install-nix-action@v26
    - name: Restore and cache Nix store
      uses: nix-community/cache-nix-action@v5
      with:
        primary-key: nix-${{ runner.os }}-
        gc-max-store-size-linux: 1073741824
        purge: true
    - uses: cachix/cachix-action@v15
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv
    - name: Run a multi-line command in the devenv shell
      shell: devenv shell bash -- -e {0}
      run: |
        hugo version
